services:
  - type: web
    name: chuchuang-company-server
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: CLIENT_URL
        value: https://pyy-space.github.io/chuchuang-company/
    plan: free